baseURL = '/'
languageCode = 'pt-pt'
title = 'Sabores da Retorta'
theme = 'resto-hugo'

# Theme specific configuration
[params]
logo = "img/logo.png"
enableDisqus = false # enable / disable comments for blog posts
enableGA = true # enable / disable google analytics
footerText = "Próximas tasquinhas:<ul><li>Semana das Associações Campo</li><li>Couce em festa</li></ul>"
facebook = "https://facebook.com/GDRRetorta"
website = "https://retorta.com"
email = "geral@retorta.com"

disableKinds = ['taxonomy']