baseURL = '/'
languageCode = 'pt-pt'
title = 'Sabores da Retorta'
theme = 'resto-hugo'

# Theme specific configuration
[params]
logo = "img/logo.png"
enableDisqus = false # enable / disable comments for blog posts
enableGA = true # enable / disable google analytics
footerText = "Próximas festividades:<br><p>Semana das Associações Campo</p><p>Couce em festa</p>"
facebook = "https://facebook.com/GDRRetorta"
website = "https://retorta.com"
email = "geral@retorta.com"

disableKinds = ['taxonomy']